sudo: false
language: go
go:
  - 1.16.x

# only last commit
git:
  depth: 1

# use vendor dependencys
install: true

notifications:
  email: false

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo/cmd/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell

script: 
  - golint `go list`
  - go test -v -race `go list`
  - go vet -v `go list`
  - gocyclo *.go
  - misspell *.go
